---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ocp402XXX
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /ocp_root/ocp402XXX
    server: nfsexport01.ti.com
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: thin
